apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis-storage
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-standard 
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true