apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: key-rotated
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000