apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: envoy-hpa
  namespace: envoy-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: envoy-gateway
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50